services:
  chronos-rabbitmq:
    image: rabbitmq:4-management
    container_name: chronos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - chronos-rabbitmq-data:/var/lib/rabbitmq

  chronos-postgres:
    image: postgres:17
    container_name: chronos-postgres
    environment:
      POSTGRES_DB: chronos_dlq
      POSTGRES_USER: chronos
      POSTGRES_PASSWORD: chronos_dev_password
    ports:
      - "5432:5432"
    volumes:
      - chronos-postgres-data:/var/lib/postgresql/data

volumes:
  chronos-rabbitmq-data:
  chronos-postgres-data: